### ISSUE TITLE
Multiple files output. All have same content.

### ISSUE THREAD

**Issue by david-hollifield** [ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator.Webpack#3]
My plugin config looks like
```
poco("./typings",
    ["../../PF Api/PhotoFinale.Api.Entities/*.cs"],
    {
        //options go here
    }
)
```
the d.ts files being created in /dist/typings, but all have the content of the last file generated (Watermark.cs in this sample). Am I missing an option?

![image](https://user-images.githubusercontent.com/686784/39588321-926b97c2-4ec9-11e8-995a-76d633cad6fa.png)

**Comment by ffMathy** [comment]
That sounds off. Can you send me a sample where you can reproduce this?

Also, pull requests are welcome.

**Comment by david-hollifield** [comment]
Here's a sample that reproduces the duplicate content issue.

in poco/pf web:
    npm install
    npm run build

[poco.zip](https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator.Webpack/files/1972315/poco.zip)

**Comment by rmacfie** [comment]
I had the same problem but the latest version, 1.0.14, solved it for me.

**Comment by ffMathy** [comment]
Yeah @david-hollifield solved the issue with a pull request. Closing this. Thanks everyone!
